2024-08-22 14:54:07 | INFO | model_worker | Loading the model ['测试模型1-14B'] on worker cb951ac1 ...
2024-08-22 14:54:07 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                                                     | 0/8 [00:00<?, ?it/s]
2024-08-22 14:54:16 | ERROR | stderr | Loading checkpoint shards:  12%|███████████████▋                                                                                                             | 1/8 [00:08<01:00,  8.65s/it]
2024-08-22 14:54:31 | ERROR | stderr | Loading checkpoint shards:  25%|███████████████████████████████▎                                                                                             | 2/8 [00:23<01:13, 12.24s/it]
2024-08-22 14:54:39 | ERROR | stderr | Loading checkpoint shards:  25%|███████████████████████████████▎                                                                                             | 2/8 [00:31<01:35, 15.84s/it]
2024-08-22 14:54:39 | ERROR | stderr | 
2024-08-22 14:54:39 | ERROR | stderr | Process model_worker - 测试模型1-14B:
2024-08-22 14:54:39 | ERROR | stderr | Traceback (most recent call last):
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-08-22 14:54:39 | ERROR | stderr |     self.run()
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-08-22 14:54:39 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-08-22 14:54:39 | ERROR | stderr |   File "/data0/jording/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-08-22 14:54:39 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-08-22 14:54:39 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/data0/jording/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-08-22 14:54:39 | ERROR | stderr |     worker = ModelWorker(
2024-08-22 14:54:39 | ERROR | stderr |              ^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-08-22 14:54:39 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-08-22 14:54:39 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-08-22 14:54:39 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-08-22 14:54:39 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 1685, in load_model
2024-08-22 14:54:39 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-08-22 14:54:39 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
2024-08-22 14:54:39 | ERROR | stderr |     return model_class.from_pretrained(
2024-08-22 14:54:39 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
2024-08-22 14:54:39 | ERROR | stderr |     ) = cls._load_pretrained_model(
2024-08-22 14:54:39 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4284, in _load_pretrained_model
2024-08-22 14:54:39 | ERROR | stderr |     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
2024-08-22 14:54:39 | ERROR | stderr |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/transformers/modeling_utils.py", line 805, in _load_state_dict_into_meta_model
2024-08-22 14:54:39 | ERROR | stderr |     set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
2024-08-22 14:54:39 | ERROR | stderr |   File "/home/jording/anaconda3/envs/security/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
2024-08-22 14:54:39 | ERROR | stderr |     new_value = value.to(device)
2024-08-22 14:54:39 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^
2024-08-22 14:54:39 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacty of 23.55 GiB of which 39.50 MiB is free. Process 197081 has 12.86 GiB memory in use. Process 197609 has 904.00 MiB memory in use. Including non-PyTorch memory, this process has 9.73 GiB memory in use. Of the allocated memory 9.36 GiB is allocated by PyTorch, and 1.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
